---

- name: Pre-reqs for ansible to run
  gather_facts: false
  become: yes
  hosts: all
  pre_tasks:
    - name: Setup pre-reqs
      raw: test -e /usr/bin/python || ( apt -y update && apt install -y python-minimal)

- name: Build
  hosts: all
  become: yes
  tasks:
    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Copy connectivity tester binary
      copy:
        src: connectivity-tester-linux-amd64
        dest: /usr/bin/connectivity-tester-linux-amd64
        owner: root
        group: root
        mode: 0755

    - name: Add a script to start it up
      copy:
        content: |
          #!/bin/bash
          env $(curl -s http://169.254.169.254/latest/user-data) /usr/bin/connectivity-tester-linux-amd64
        dest: /usr/bin/connectivity-tester-linux-amd64-starter.sh
        owner: root
        group: root
        mode: 0755

    - name: Make Cron Job to start it on boot
      cron:
        name: Start Connectivity Tester
        special_time: reboot
        job: /usr/bin/connectivity-tester-linux-amd64-starter.sh

    - name: Copy cloudwatch healthchecker
      copy:
        src: reporthealth.sh
        dest: /usr/bin/reporthealth.sh
        owner: root
        group: root
        mode: 0755

    - name: Cloudwatch metrics Cron Job
      cron:
        name: Cloudwatch metrics
        job: /usr/bin/reporthealth.sh


    - name: Copy cloudwatch healthchecker
      copy:
        src: reporthealth.sh
        dest: /usr/bin/reporthealth.sh
        owner: root
        group: root
        mode: 0755

    - name: Cloudwatch metrics Cron Job
      cron:
        name: Cloudwatch metrics
        job: /usr/bin/reporthealth.sh


    - name: Download cloudwatch logs agent
      get_url:
        url: https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
        dest: /tmp/awslogs-agent-setup.py
        mode: "+x"

    - name: Cloudwatch logs config
      copy:
        dest: /tmp/cwlogs.conf
        content: |
          [general]
          state_file = /var/awslogs/state/agent-state

          [/var/log/syslog]
          file = /var/log/syslog
          log_group_name = /connectivity_tester/system
          log_stream_name = {instance_id}
          datetime_format = %b %d %H:%M:%S

          [/connectivity_tester/cloud-init]
          file = /var/log/cloud-init.log
          log_group_name = /connectivity_tester/cloud-init
          log_stream_name = {instance_id}
          datetime_format = %Y-%m-%d %H:%M:%S,%f

          [/connectivity_tester/cloud-init/output]
          file = /var/log/cloud-init-output.log
          log_group_name = /connectivity_tester/cloud-init/output
          log_stream_name = {instance_id}
          datetime_format = %Y-%m-%d %H:%M:%S,%f

    - name: Install cloudwatch log agent
      environment:
        LC_ALL: C
      shell: /tmp/awslogs-agent-setup.py --region eu-west-2 --non-interactive -c /tmp/cwlogs.conf
      args:
        creates: /var/awslogs/etc/aws.conf

    - name: Copy cloudwatch logs starter
      copy:
        src: startcloudwatchlogs.sh
        dest: /usr/bin/startcloudwatchlogs.sh
        owner: root
        group: root
        mode: 0755

    - name: Make Cron Job to start awslogs with right region
      cron:
        name: Start awslogs
        special_time: reboot
        job: /usr/bin/startcloudwatchlogs.sh

- name: Test
  hosts: all
  tasks:
    - name: Start
      become: yes
      shell: /usr/bin/connectivity-tester-linux-amd64
      environment:
        LISTEN_http: 0.0.0.0:80
        CHECK_local: 127.0.0.1:80
      async: 60
      poll: 0
    - name: Test
      uri:
        url: http://127.0.0.1:80