---

- name: Pre-reqs for ansible to run
  gather_facts: false
  become: yes
  hosts: all
  pre_tasks:
    - name: Setup pre-reqs
      raw: test -e /usr/bin/python || ( apt -y update && apt install -y python-minimal)

- name: Build
  hosts: all
  become: yes
  tasks:
    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Copy connectivity tester binary
      copy:
        src: connectivity-tester-linux-amd64
        dest: /usr/bin/connectivity-tester-linux-amd64
        owner: root
        group: root
        mode: 0755

    - name: Add a script to start it up
      copy:
        content: |
          #!/bin/bash
          env $(curl -s http://169.254.169.254/latest/user-data) /usr/bin/connectivity-tester-linux-amd64
        dest: /usr/bin/connectivity-tester-linux-amd64-starter.sh
        owner: root
        group: root
        mode: 0755

    - name: Make Cron Job to start it on boot
      cron:
        name: Start Connectivity Tester
        special_time: reboot
        job: /usr/bin/connectivity-tester-linux-amd64-starter.sh

    - name: Copy cloudwatch healthchecker
      copy:
        src: reporthealth.sh
        dest: /usr/bin/reporthealth.sh
        owner: root
        group: root
        mode: 0755

    - name: Cloudwatch metrics Cron Job
      cron:
        name: Cloudwatch metrics
        job: /usr/bin/reporthealth.sh
        user: nobody

#- name: Test
#  hosts: all
#  tasks:
#    - name: Start
#      shell: LISTEN_http=0.0.0.0:80 CHECK_local=127.0.0.1:80 /usr/bin/connectivity-tester-linux-amd64
#      async: 60
#      poll: 0
#    - name: Test
#      shell: curl http://localhost
#
# uri:
#        url: http://127.0.0